# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DeepZoomStore": "01_deepzoom.ipynb",
         "upload": "01_deepzoom.ipynb",
         "make_html": "01_deepzoom.ipynb",
         "connect_b2_bucket": "01_deepzoom.ipynb",
         "dzp_save": "01_deepzoom.ipynb",
         "dzi_to_js": "01_deepzoom.ipynb",
         "create_multiviewer": "01_deepzoom.ipynb",
         "ROOTDIR": "01_deepzoom.ipynb",
         "VIEWERSDIR": "01_deepzoom.ipynb"}

modules = ["deepzoom.py"]

doc_url = "https://fligt.github.io/deepzoomup/"

git_url = "https://github.com/fligt/deepzoomup/tree/master/"

def custom_doc_links(name): return None
