# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dzi_html_template": "02_deepzoom.ipynb",
         "dzi_js_template": "02_deepzoom.ipynb",
         "viewer_div_template": "02_deepzoom.ipynb",
         "callback_js_template": "02_deepzoom.ipynb",
         "callback_div_template": "02_deepzoom.ipynb",
         "upload": "02_deepzoom.ipynb",
         "make_html": "02_deepzoom.ipynb",
         "connect_b2_bucket": "02_deepzoom.ipynb",
         "dzp_save": "02_deepzoom.ipynb",
         "dzi_to_js": "02_deepzoom.ipynb",
         "dzp_thumbnail": "02_deepzoom.ipynb",
         "list_names": "02_deepzoom.ipynb",
         "stack_image_json": "02_deepzoom.ipynb",
         "viewer_div": "02_deepzoom.ipynb",
         "callback_viewer": "02_deepzoom.ipynb",
         "DeepZoomStore": "02_deepzoom.ipynb",
         "ROOTDIR": "02_deepzoom.ipynb",
         "VIEWERSDIR": "02_deepzoom.ipynb"}

modules = ["deepzoom.py"]

doc_url = "https://fligt.github.io/deepzoomup/"

git_url = "https://github.com/fligt/deepzoomup/tree/master/"

def custom_doc_links(name): return None
